// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace StyleCssNamespace {
  export interface IStyleCss {
    home: string
    ipList: string
  }
}

declare const StyleCssModule: StyleCssNamespace.IStyleCss

export = StyleCssModule
